# Permalinks
permalink:      /:year-:month-:day/:title

#pagination
paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/page:num/'
    sub_dir: '/blog'
  - paginate: 5
    paginate_path: '/writings/page:num/'
    sub_dir: '/writings'
  - paginate: 10
    paginate_path: '/quotes/page:num'
    sub_dir: '/quotes'



# Setup
title:          Ankit Solanki
baseurl:        "/space"
url:            "https://techcentaur.github.io/space"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Ankit Solanki
  email:        ankit03june@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/techcentaur/space

# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-multiple



#usernames
twitter_username:     theboywhosawit
github_username:      techcentaur
linkedin_username:    ankitsolanki03
facebook_username:    https://www.facebook.com/profile.php?id=100012319235305
instagram_username:   ank.it42
gmail_address:        ankit03june@gmail.com

