# Permalinks
permalink:      /:year-:month-:day/:title

#pagination
paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/page:num/'
    sub_dir: '/blog'
  - paginate: 5
    paginate_path: '/writings/page:num/'
    sub_dir: '/writings'
  - paginate: 10
    paginate_path: '/quotes/page:num'
    sub_dir: '/quotes'



# Setup
title:          Ankit Solanki
baseurl:        "/space"
url:            "https://techcentaur.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Ankit Solanki
  email:        ankit03june@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/techcentaur/Spacetime

# Gems
gems:
  - jekyll-paginate
  - jekyll-paginate-multiple



#usernames
twitter_username:     r3bl_
github_username:      aleksandar-todorovic
linkedin_username:    aleksandartodorovic
facebook_username:    aleksandar.todorovic.r3bl
instagram_username:   username
gmail_address:        gmail

